### ISSUE TITLE
"No events found" Error

### ISSUE THREAD

**Issue by kirstenkeister** [thecity/thecity-plaza-wordpress#24]
Due to what I believe is a change in the properties of the feed being pulled into this plugin, the plugin no longer works and simply shows "No events found" text, despite there being verified events available. 

I have no idea whether this plugin is being developed or supported any longer, but we use it extensively on our site and it's frustrating to have it simply stop working!

**Comment by kirstenkeister** [comment]
Resolved by updating to latest version from github which includes https:// changes

**Comment by weshays** [comment]
The latest version 0.8.6 - now pushed to wordpress.org - contains the update.
